server:
  port: 8080
zuul:
  ignoredServices: '*'
  routes:
    api:
      path: /api/**
      serviceId: collector

collector:
  path: /graphql
  ribbon:
    listOfServers: 127.0.0.1:10800
    NIWSServerListClassName: org.apache.skywalking.apm.webapp.tools.CollectorServerList
