#cluster:
#  zookeeper:
#    hostPort: localhost:2181
#    sessionTimeout: 100000
naming:
  jetty:
    host: localhost
    port: 10800
    context_path: /
remote:
  gRPC:
    host: localhost
    port: 11800
agent_gRPC:
  gRPC:
    host: localhost
    port: 11800
agent_jetty:
  jetty:
    host: localhost
    port: 12800
    context_path: /
analysis_register:
  default:
analysis_jvm:
  default:
analysis_segment_parser:
  default:
    buffer_file_path: ../buffer/
    buffer_offset_max_file_size: 10M
    buffer_segment_max_file_size: 500M
ui:
  jetty:
    host: localhost
    port: 12800
    context_path: /
storage:
  elasticsearch:
    cluster_name: CollectorDBCluster
    cluster_transport_sniffer: true
    cluster_nodes: localhost:9300
    index_shards_number: 2
    index_replicas_number: 0
    ttl: 7
#storage:
#  h2:
#    url: jdbc:h2:tcp://localhost/~/test
#    user_name: sa
configuration:
  default:
    application_apdex_threshold: 2000
    service_error_rate_threshold: 10.00
    service_average_response_time_threshold: 2000
    instance_error_rate_threshold: 10.00
    instance_average_response_time_threshold: 2000
    application_error_rate_threshold: 10.00
    application_average_response_time_threshold: 2000